### ISSUE TITLE
`.transaction()` throws error `Zone` not defined.

### ISSUE THREAD

**Issue by adamduren** [blaugold/firebase-rxjs#2]
I stumbled upon this issue when using this library and did some debugging and searched the codebase and the only place I found the `if (Zone)` construct was here so I'm guessing it was leftover from adding the zone helper. Removing these lines should fix the issue. 

https://github.com/blaugold/firebase-rxjs/blob/e84fab84f970d52d626c637ee4f65e92f6eb7fce/packages/firebase-rxjs/src/database.ts#L258-L260

Great library by the way!

**Comment by blaugold** [comment]
Glad you like the library and thanks for reporting this issue. The problem was the way I checked for the global variable `Zone`. I refactored the wrapping of the `transactionHandler` into the zone helper.
